chore: rm unused var
Not sure why the cvm update causes this

```
In file included from external/rv_tester/cosim/utils/eot/eot.cpp:1:
external/rv_tester/cosim/utils/eot/eot.h:67:35: error: private field 'elapsed_seconds' is not used [-Werror,-Wunused-private-field]
    std::chrono::duration<double> elapsed_seconds;
```